version: '3.8'
services:
  influxdb:
    image: influxdb
    container_name: influxdb
    ports:
      - "8086:8086"
    restart: always
    networks:
      - influxdb_network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    restart: always
    networks:
      - influxdb_network

  nats:
    image: nats
    container_name: nats
    ports:
      - "4222:4222"
    restart: always
    networks:
      - influxdb_network

  ekuiper:
    image: lfedge/ekuiper:latest
    container_name: ekuiper
    volumes:
      - ./ekuiper/config:/etc/ekuiper/config
      - ./ekuiper/rules:/etc/ekuiper/rules
    restart: always
    networks:
      - influxdb_network

networks:
  influxdb_network:
    driver: bridge
