version: '3.8'

services:
  
   

  mongo:
    image: mongo
    ports:
      - "27018:27018"
    

  javascript:
    image: js-image:js2
    ports:
      - "3000:3000"

  dotnet:
    image: dotnet-image4
    ports:
      - "5087:5087"
